<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\RoomSchedule;
use Illuminate\Support\Facades\DB;

class AcademicScheduleSeeder extends Seeder
{
    public function run()
    {
        // Ambil ID ruangan yang sudah di-seed
        $roomA21 = DB::table('rooms')->where('room_number', 'A2.1')->first();
        $roomA22 = DB::table('rooms')->where('room_number', 'A2.2')->first();
        $roomA23 = DB::table('rooms')->where('room_number', 'A2.3')->first();
        $roomA24 = DB::table('rooms')->where('room_number', 'A2.4')->first();
        $roomA25 = DB::table('rooms')->where('room_number', 'A2.5')->first();
        $roomD11 = DB::table('rooms')->where('room_number', 'D1.1')->first();
        $roomD12 = DB::table('rooms')->where('room_number', 'D1.2')->first();
        $roomD13 = DB::table('rooms')->where('room_number', 'D1.3')->first();
        $roomD14 = DB::table('rooms')->where('room_number', 'D1.4')->first();
        $roomB11 = DB::table('rooms')->where('room_number', 'B1.1')->first();
        $roomC11 = DB::table('rooms')->where('room_number', 'C1.1')->first();
        $roomC22 = DB::table('rooms')->where('room_number', 'C2.2')->first();
        $roomC23 = DB::table('rooms')->where('room_number', 'C2.3')->first();
        $roomE21 = DB::table('rooms')->where('room_number', 'E2.1')->first();
        $roomE22 = DB::table('rooms')->where('room_number', 'E2.2')->first();

        // Data jadwal terstruktur
        $data = [
            // Ruangan A2.1
            [
                'room_id' => $roomA21->id,
                'activity_name' => 'METODOLOGI PENELITIAN',
                'schedule_type' => 'Academic',
                'day_of_week' => 'Senin',
                'start_time' => '09:30',
                'end_time' => '12:00',
                'lecturer' => 'WANA PRAMUDYAWARDANA KUSUMA N.',
                'class_name' => 'F13.601',
                'status' => 'approved',
            ],
            [
                'room_id' => $roomA21->id,
                'activity_name' => 'ANALISA DAN PERANCANGAN SISTEM INFORMASI',
                'class_name' => 'F12.D401',
                'day_of_week' => 'Senin',
                'start_time' => '12:30',
                'end_time' => '14:10',
                'lecturer' => 'ERBA LUTFINA, S.Kom, M.Kom',
                'schedule_type' => 'Academic',
                'status' => 'approved',
            ],
            [
                'room_id' => $roomA21->id,
                'activity_name' => 'AKUNTANSI PENGANTAR II',
                'class_name' => 'F13.202',
                'day_of_week' => 'Senin',
                'start_time' => '16:20',
                'end_time' => '18:00',
                'lecturer' => 'Dr. ICHWAN SETIARSO, M.P',
                'schedule_type' => 'Academic',
                'status' => 'approved',
            ],
            [
                'room_id' => $roomA21->id,
                'activity_name' => 'PEMROGRAMAN BERORIENTASI OBJEK',
                'class_name' => 'F11.C402',
                'day_of_week' => 'Senin',
                'start_time' => '18:30',
                'end_time' => '20:10',
                'lecturer' => 'ZUDHA PRATAMA, S.Kom, M.Kom',
                'schedule_type' => 'Academic',
                'status' => 'approved',
            ],
            [
                'room_id' => $roomA21->id,
                'activity_name' => 'EKONOMI INTERNASIONAL',
                'class_name' => 'F13.201',
                'day_of_week' => 'Selasa',
                'start_time' => '07:00',
                'end_time' => '09:30',
                'lecturer' => 'MAHADIKA PRADIPTA HIMAWAN S.Pad',
                'schedule_type' => 'Academic',
                'status' => 'approved',
            ],
            [
                'room_id' => $roomA21->id,
                'activity_name' => 'PRAKTIKUM MANAJEMEN SUMBER DAYA',
                'class_name' => 'F13.201',
                'day_of_week' => 'Selasa',
                'start_time' => '09:30',
                'end_time' => '12:00',
                'lecturer' => 'TRI ESTI RAHAYUNINGTYAS, S.E., _',
                'schedule_type' => 'Academic',
                'status' => 'approved',
            ],
            [
                'room_id' => $roomA21->id,
                'activity_name' => 'PRAKTIKUM MANAJEMEN SUMBER DAYA',
                'class_name' => 'F13.202',
                'day_of_week' => 'Selasa',
                'start_time' => '15:30',
                'end_time' => '18:00',
                'lecturer' => 'TRI ESTI RAHAYUNINGTYAS, S.E., _',
                'schedule_type' => 'Academic',
                'status' => 'approved',
            ],
            [
                'room_id' => $roomA21->id,
                'activity_name' => 'PENGANTAR EKONOMI MIKRO',
                'class_name' => 'F13.202',
                'day_of_week' => 'Selasa',
                'start_time' => '18:30',
                'end_time' => '21:00',
                'lecturer' => 'WANA PRAMUDYAWARDANA KUSUMA N.',
                'schedule_type' => 'Academic',
                'status' => 'approved',
            ],
            [
                'room_id' => $roomA21->id,
                'activity_name' => 'MANAJEMEN STRATEGIK',
                'class_name' => 'F13.401',
                'day_of_week' => 'Rabu',
                'start_time' => '07:00',
                'end_time' => '09:30',
                'lecturer' => 'CHOERUL UMAM, S.Kom., M.M',
                'schedule_type' => 'Academic',
                'status' => 'approved',
            ],
            [
                'room_id' => $roomA21->id,
                'activity_name' => 'PROYEK PERANGKAT LUNAK',
                'class_name' => 'F11.C401',
                'day_of_week' => 'Rabu',
                'start_time' => '12:30',
                'end_time' => '15:00',
                'lecturer' => 'ZUDHA PRATAMA, S.Kom., M.Kom',
                'schedule_type' => 'Academic',
                'status' => 'approved',
            ],
            [
                'room_id' => $roomA21->id,
                'activity_name' => 'STATISTIKA',
                'class_name' => 'F13.202',
                'day_of_week' => 'Rabu',
                'start_time' => '18:30',
                'end_time' => '21:00',
                'lecturer' => 'AMALIA NUR CHASANAH, SE, MM',
                'schedule_type' => 'Academic',
                'status' => 'approved',
            ],
            [
                'room_id' => $roomA21->id,
                'activity_name' => 'PENGANTAR EKONOMI MIKRO',
                'class_name' => 'F13.201',
                'day_of_week' => 'Kamis',
                'start_time' => '09:30',
                'end_time' => '12:00',
                'lecturer' => 'Dr. AGUS PRAYITNO, Drs., M.M.',
                'schedule_type' => 'Academic',
                'status' => 'approved',
            ],
            [
                'room_id' => $roomA21->id,
                'activity_name' => 'HUKUM BISNIS',
                'class_name' => 'F13.201',
                'day_of_week' => 'Kamis',
                'start_time' => '12:30',
                'end_time' => '14:10',
                'lecturer' => 'WIDYATMOKO, S.Kom., M.M',
                'schedule_type' => 'Academic',
                'status' => 'approved',
            ],
            [
                'room_id' => $roomA21->id,
                'activity_name' => 'HUKUM BISNIS',
                'class_name' => 'F13.202',
                'day_of_week' => 'Kamis',
                'start_time' => '16.20',
                'end_time' => '18:00',
                'lecturer' => '	WIDYATMOKO, S.Kom., M.M',
                'schedule_type' => 'Academic',
                'status' => 'approved',
            ],
            [
                'room_id' => $roomA21->id,
                'activity_name' => 'PROYEK PERANGKAT LUNAK',
                'class_name' => 'F11.C402',
                'day_of_week' => 'Kamis',
                'start_time' => '18:30',
                'end_time' => '21:00',
                'lecturer' => 'ZUDHA PRATAMA, S.Kom., M.Kom',
                'schedule_type' => 'Academic',
                'status' => 'approved',
            ],
            [
                'room_id' => $roomA21->id,
                'activity_name' => 'RANGKAIAN LOGIKA DIGITAL',
                'schedule_type' => 'Academic',
                'day_of_week' => 'Jumat',
                'start_time' => '08:40',
                'end_time' => '10:20',
                'lecturer' => 'WILDAN MAHMUD, S.Kom., M.MT',
                'class_name' => 'F11.C201',
                'status' => 'approved',
            ],
            [
                'room_id' => $roomA21->id,
                'activity_name' => 'PENDIDIKAN PANCASILA',
                'schedule_type' => 'Academic',
                'day_of_week' => 'Jumat',
                'start_time' => '12:30',
                'end_time' => '14:10',
                'lecturer' => 'IQLIMA ZAHARI, S.Pd.I, M.Pd.I',
                'class_name' => 'F14.E601',
                'status' => 'approved',
            ],
            [
                'room_id' => $roomA21->id,
                'activity_name' => 'BIMBINGAN KARIR',
                'schedule_type' => 'Academic',
                'day_of_week' => 'Sabtu',
                'start_time' => '12:30',
                'end_time' => '15:00',
                'lecturer' => 'GILANG RIZKY GARDIANTO, S.DS, M.Pd',
                'class_name' => 'F13.601',
                'status' => 'approved',
            ],

            // Ruangan A2.2
            [
                'room_id' => $roomA22->id,
                'activity_name' => 'PENDIDIKAN AGAMA ISLAM',
                'class_name' => 'F13.601',
                'day_of_week' => 'Senin',
                'start_time' => '07:00',
                'end_time' => '08:40',
                'lecturer' => 'CHOERUL UMAM, S.Kom., M.M',
                'schedule_type' => 'Academic',
                'status' => 'approved',
            ],
            [
                'room_id' => $roomA22->id,
                'activity_name' => 'PRAKTIKUM MANAJEMEN PEMASARAN',
                'class_name' => 'F13.401',
                'day_of_week' => 'Senin',
                'start_time' => '09:20',
                'end_time' => '12:00',
                'lecturer' => 'TRI ESTI RAHAYUNINGTYAS, S.E., _',
                'schedule_type' => 'Academic',
                'status' => 'approved',
            ],
            [
                'room_id' => $roomA22->id,
                'activity_name' => 'REKAYASA PERANGKAT LUNAK',
                'class_name' => 'F11.C201',
                'day_of_week' => 'Senin',
                'start_time' => '12:30',
                'end_time' => '15:00',
                'lecturer' => 'WIDYATMOKO, S.Kom., M.M',
                'schedule_type' => 'Academic',
                'status' => 'approved',
            ],
            [
                'room_id' => $roomA22->id,
                'activity_name' => 'PROBABILITAS DAN STATISTIKA',
                'class_name' => 'F11.C402',
                'day_of_week' => 'Senin',
                'start_time' => '15:30',
                'end_time' => '18:00',
                'lecturer' => 'DIBYO ADI WIBOWO, S.Si, M.Si',
                'schedule_type' => 'Academic',
                'status' => 'approved',
            ],
            [
                'room_id' => $roomA22->id,
                'activity_name' => 'EKONOMI INTERNASIONAL',
                'class_name' => 'F13.202',
                'day_of_week' => 'Senin',
                'start_time' => '16:30',
                'end_time' => '21:00',
                'lecturer' => 'MAHADIKA PRADIPTA HIMAWAN, S.Pa',
                'schedule_type' => 'Academic',
                'status' => 'approved',
            ],
            [
                'room_id' => $roomA22->id,
                'activity_name' => 'PENDIDIKAN PANCASILA',
                'class_name' => 'F12.D601',
                'day_of_week' => 'Selasa',
                'start_time' => '10:20',
                'end_time' => '12:00',
                'lecturer' => 'IQLIMA ZAHARI, S.Pd.I, M.Pd.I',
                'schedule_type' => 'Academic',
                'status' => 'approved',
            ],
            [
                'room_id' => $roomA22->id,
                'activity_name' => 'DATA MINING',
                'class_name' => 'F11.C402',
                'day_of_week' => 'Selasa',
                'start_time' => '18:30',
                'end_time' => '21:00',
                'lecturer' => 'GALUH WILUJENG SARASWATI, M.Si',
                'schedule_type' => 'Academic',
                'status' => 'approved',
            ],
            [
                'room_id' => $roomA22->id,
                'activity_name' => 'KALKULUS 2',
                'class_name' => 'F11.C601',
                'day_of_week' => 'Rabu',
                'start_time' => '12:40',
                'end_time' => '14:10',
                'lecturer' => 'DIBYO ADI WIBOWO, S.Si, M.Si',
                'schedule_type' => 'Academic',
                'status' => 'approved',
            ],
            [
                'room_id' => $roomA22->id,
                'activity_name' => 'FISIKA 1',
                'class_name' => 'F13.202',
                'day_of_week' => 'Rabu',
                'start_time' => '16:20',
                'end_time' => '18:00',
                'lecturer' => 'Dr. DIDIK HERMANTO, S.T., M.Pd',
                'schedule_type' => 'Academic',
                'status' => 'approved',
            ],
            [
                'room_id' => $roomA22->id,
                'activity_name' => 'RISET PEMASARAN',
                'class_name' => 'F13.601',
                'day_of_week' => 'Kamis',
                'start_time' => '07:00',
                'end_time' => '09:30',
                'lecturer' => 'WANA PRAMUDYAWARDANA KUSUMA NEG',
                'schedule_type' => 'Academic',
                'status' => 'approved',
            ],
            [
                'room_id' => $roomA22->id,
                'activity_name' => 'BAHASA INGGRIS',
                'class_name' => 'F13.601',
                'day_of_week' => 'Kamis',
                'start_time' => '12:30',
                'end_time' => '14:40',
                'lecturer' => 'ANISA LARASSATI, S.S., M.Ling',
                'schedule_type' => 'Academic',
                'status' => 'approved',
            ],
            [
                'room_id' => $roomA22->id,
                'activity_name' => 'SINEMATOGRAFI',
                'class_name' => 'F14.E402',
                'day_of_week' => 'Kamis',
                'start_time' => '16:20',
                'end_time' => '18:00',
                'lecturer' => 'ADHITYA CANDRA IRAWAN, M.Sn',
                'schedule_type' => 'Academic',
                'status' => 'approved',
            ],
            [
                'room_id' => $roomA22->id,
                'activity_name' => 'PRAKTIKUM MANAJEMEN KEUANGAN',
                'class_name' => 'F13.401',
                'day_of_week' => 'Jumat',
                'start_time' => '07:00',
                'end_time' => '09:30',
                'lecturer' => 'AMALIA NUR CHASANAH, S.E., M.M',
                'schedule_type' => 'Academic',
                'status' => 'approved',
            ],
            [
                'room_id' => $roomA22->id,
                'activity_name' => 'TUGAS AKHIR',
                'class_name' => 'F13.801',
                'day_of_week' => 'Jumat',
                'start_time' => '18:30',
                'end_time' => '21:00',
                'lecturer' => 'MOCH. SJAMSUL HIDAJAT, S.E., M.M',
                'schedule_type' => 'Academic',
                'status' => 'approved',
            ],

            // Ruangan A2.3
            [
                'room_id' => $roomA23->id,
                'activity_name' => 'SISTEM OPERASI',
                'class_name' => 'F11.C401',
                'day_of_week' => 'Senin',
                'start_time' => '09:30',
                'end_time' => '12:00',
                'lecturer' => 'MOCH. SJAMSUL HIDAJAT, S.E., M.M',
                'schedule_type' => 'Academic',
                'status' => 'approved',
            ],
            [
                'room_id' => $roomA23->id,
                'activity_name' => 'PEMROGRAMAN BERORIENTASI',
                'class_name' => 'F11.C401',
                'day_of_week' => 'Senin',
                'start_time' => '12:30',
                'end_time' => '14:10',
                'lecturer' => 'ZUDHA PRATAMA, S.Kom., M.Kom',
                'schedule_type' => 'Academic',
                'status' => 'approved',
            ],
            [
                'room_id' => $roomA23->id,
                'activity_name' => 'LOGIKA INFORMATIKA',
                'class_name' => 'F11.C201',
                'day_of_week' => 'Selasa',
                'start_time' => '09:30',
                'end_time' => '12:00',
                'lecturer' => 'ACHMAD WAHID KURNIAWAN, S.Si, M.M',
                'schedule_type' => 'Academic',
                'status' => 'approved',
            ],
            [
                'room_id' => $roomA23->id,
                'activity_name' => 'ALGORITMA DAN PEMROGRAMAN',
                'class_name' => 'F11.C201',
                'day_of_week' => 'Selasa',
                'start_time' => '12:30',
                'end_time' => '14:10',
                'lecturer' => 'EKO HARI RACHMAWANTO, M.Kom',
                'schedule_type' => 'Academic',
                'status' => 'approved',
            ],
            [
                'room_id' => $roomA23->id,
                'activity_name' => 'ALGORITMA DAN PEMROGRAMAN',
                'class_name' => 'F11.C202',
                'day_of_week' => 'Selasa',
                'start_time' => '16:20',
                'end_time' => '18:00',
                'lecturer' => 'EKO HARI RACHMAWANTO, M.Kom',
                'schedule_type' => 'Academic',
                'status' => 'approved',
            ],
            [
                'room_id' => $roomA23->id,
                'activity_name' => 'KRIPTOGRAFI',
                'class_name' => 'F11.C601',
                'day_of_week' => 'Rabu',
                'start_time' => '09:30',
                'end_time' => '12:00',
                'lecturer' => 'EKO HARI RACHMAWANTO, M.Kom',
                'schedule_type' => 'Academic',
                'status' => 'approved',
            ],
            [
                'room_id' => $roomA23->id,
                'activity_name' => 'ETIKA PROFESI',
                'class_name' => 'F12.D601',
                'day_of_week' => 'Rabu',
                'start_time' => '12:30',
                'end_time' => '14:10',
                'lecturer' => 'IQLIMA ZAHARI, S.Pd.I, M.Pd.I',
                'schedule_type' => 'Academic',
                'status' => 'approved',
            ],
            [
                'room_id' => $roomA23->id,
                'activity_name' => 'DESAIN KOMUNIKASI VISUAL',
                'class_name' => 'F14.E601',
                'day_of_week' => 'Kamis',
                'start_time' => '10:20',
                'end_time' => '12:00',
                'lecturer' => 'GILANG RIZKY GARDIANTO, S.DS, M.Kom',
                'schedule_type' => 'Academic',
                'status' => 'approved',
            ],
            [
                'room_id' => $roomA23->id,
                'activity_name' => 'INFRASTRUKTUR TEKNOLOGI I',
                'class_name' => 'F12.D201',
                'day_of_week' => 'Kamis',
                'start_time' => '12:30',
                'end_time' => '14:10',
                'lecturer' => 'CHOERUL UMAM, S.Kom., M.M',
                'schedule_type' => 'Academic',
                'status' => 'approved',
            ],
            [
                'room_id' => $roomA23->id,
                'activity_name' => 'DASAR KEWIRAUSAHAAN',
                'class_name' => 'F14.E202',
                'day_of_week' => 'Kamis',
                'start_time' => '18:30',
                'end_time' => '20:10',
                'lecturer' => 'GILANG RIZKY GARDIANTO, S.DS, M.Kom',
                'schedule_type' => 'Academic',
                'status' => 'approved',
            ],
            [
                'room_id' => $roomA23->id,
                'activity_name' => 'PROBABILITAS DAN STATISTIKA',
                'class_name' => 'F12.D201',
                'day_of_week' => 'Jumat',
                'start_time' => '09:30',
                'end_time' => '12:00',
                'lecturer' => 'KARMILA, S.Si, M.Kom',
                'schedule_type' => 'Academic',
                'status' => 'approved',
            ],

            // Ruangan A2.4


            // Ruangan A2.5
            [
                'room_id' => $roomA25->id,
                'activity_name' => 'PERENCANAAN SUMBER DAYA P',
                'class_name' => 'F12.D201',
                'day_of_week' => 'Senin',
                'start_time' => '09:30',
                'end_time' => '12:00',
                'lecturer' => 'WILDAN MAHMUD, S.Kom., M.MT',
                'schedule_type' => 'Academic',
                'status' => 'approved',
            ],
            [
                'room_id' => $roomA25->id,
                'activity_name' => 'BAHASA INDONESIA',
                'class_name' => 'F12.D601',
                'day_of_week' => 'Senin',
                'start_time' => '12:30',
                'end_time' => '14:00',
                'lecturer' => 'IQLIMA ZAHARI, S.Pd.I, M.Pd.I',
                'schedule_type' => 'Academic',
                'status' => 'approved',
            ],
            [
                'room_id' => $roomA25->id,
                'activity_name' => 'BAHASA INDONESIA',
                'class_name' => 'F14.E601',
                'day_of_week' => 'Senin',
                'start_time' => '14:30',
                'end_time' => '16:00',
                'lecturer' => 'IQLIMA ZAHARI, S.Pd.I, M.Pd.I',
                'schedule_type' => 'Academic',
                'status' => 'approved',
            ],
            [
                'room_id' => $roomA25->id,
                'activity_name' => 'REKAYASA PERANCANGAN LUNAK',
                'class_name' => 'F11.C201',
                'day_of_week' => 'Senin',
                'start_time' => '16:30',
                'end_time' => '18:00',
                'lecturer' => 'WIDYATMOKO, S.Kom., M.M',
                'schedule_type' => 'Academic',
                'status' => 'approved',
            ],
            [
                'room_id' => $roomA25->id,
                'activity_name' => 'PROBABILITAS DAN STATISTIKA',
                'class_name' => 'F11.C401',
                'day_of_week' => 'Selasa',
                'start_time' => '09:30',
                'end_time' => '12:00',
                'lecturer' => 'WILDAN MAHMUD, S.Kom., M.MT',
                'schedule_type' => 'Academic',
                'status' => 'approved',
            ],
            [
                'room_id' => $roomA25->id,
                'activity_name' => 'SISTEM OPERASI',
                'class_name' => 'F11.C401',
                'day_of_week' => 'Selasa',
                'start_time' => '12:30',
                'end_time' => '14:00',
                'lecturer' => 'MOCH. SJAMSUL HIDAJAT, S.E., M.M',
                'schedule_type' => 'Academic',
                'status' => 'approved',
            ],
            [
                'room_id' => $roomA25->id,
                'activity_name' => 'TEKNIK PENGAMBILAN KEPUTUSAN',
                'class_name' => 'F12.D601',
                'day_of_week' => 'Rabu',
                'start_time' => '12:30',
                'end_time' => '14:00',
                'lecturer' => 'IQLIMA ZAHARI, S.Pd.I, M.Pd.I',
                'schedule_type' => 'Academic',
                'status' => 'approved',
            ],
            [
                'room_id' => $roomA25->id,
                'activity_name' => 'METODOLOGI PENELITIAN',
                'class_name' => 'F12.D601',
                'day_of_week' => 'Rabu',
                'start_time' => '16:20',
                'end_time' => '18:00',
                'lecturer' => 'GALUH WILUJENG SARASWATI, M.Si',
                'schedule_type' => 'Academic',
                'status' => 'approved',
            ],
            [
                'room_id' => $roomA25->id,
                'activity_name' => 'SISTEM PENDUKUNG KEPUTUSAN',
                'class_name' => 'F11.C202',
                'day_of_week' => 'Kamis',
                'start_time' => '12:30',
                'end_time' => '14:00',
                'lecturer' => 'DIBYO ADI WIBOWO, S.Si, M.Si',
                'schedule_type' => 'Academic',
                'status' => 'approved',
            ],
            [
                'room_id' => $roomA25->id,
                'activity_name' => 'OTOMATA DAN TEORI BAHASA',
                'class_name' => 'F11.C202',
                'day_of_week' => 'Kamis',
                'start_time' => '16:30',
                'end_time' => '18:00',
                'lecturer' => 'DIBYO ADI WIBOWO, S.Si, M.Si',
                'schedule_type' => 'Academic',
                'status' => 'approved',
            ],
            [
                'room_id' => $roomA25->id,
                'activity_name' => 'FISIKA 1',
                'class_name' => 'F11.C401',
                'day_of_week' => 'Jumat',
                'start_time' => '09:30',
                'end_time' => '12:00',
                'lecturer' => 'GALUH WILUJENG SARASWATI, M.Si',
                'schedule_type' => 'Academic',
                'status' => 'approved',
            ],
            [
                'room_id' => $roomA25->id,
                'activity_name' => 'DATA MINING',
                'class_name' => 'F11.C401',
                'day_of_week' => 'Jumat',
                'start_time' => '12:30',
                'end_time' => '15:00',
                'lecturer' => 'GALUH WILUJENG SARASWATI, M.Si',
                'schedule_type' => 'Academic',
                'status' => 'approved',
            ],


            // Ruangan D1.1
            [
                'room_id' => $roomD11->id,
                'activity_name' => 'AKUNTANSI PENGANTAR II',
                'class_name' => 'F13.201',
                'day_of_week' => 'Senin',
                'start_time' => '08:40',
                'end_time' => '10:20',
                'lecturer' => 'Dr. ICHWAN SETIARSO, M.P.',
                'schedule_type' => 'Academic',
                'status' => 'approved',
            ],
            [
                'room_id' => $roomD11->id,
                'activity_name' => 'PENDIDIKAN PANCASILA',
                'class_name' => 'F11.C601',
                'day_of_week' => 'Senin',
                'start_time' => '10:20',
                'end_time' => '12:00',
                'lecturer' => 'IQLIMA ZAHARI, S.Pd.I, M.Pd.I',
                'schedule_type' => 'Academic',
                'status' => 'approved',
            ],
            [
                'room_id' => $roomD11->id,
                'activity_name' => 'SEJARAH DKV',
                'class_name' => 'F14.E201',
                'day_of_week' => 'Senin',
                'start_time' => '12:30',
                'end_time' => '14:10',
                'lecturer' => 'Dr. ICHWAN SETIARSO, M.P.',
                'schedule_type' => 'Academic',
                'status' => 'approved',
            ],
            [
                'room_id' => $roomD11->id,
                'activity_name' => 'BASIS DATA',
                'class_name' => 'F11.C202',
                'day_of_week' => 'Senin',
                'start_time' => '18:30',
                'end_time' => '20:10',
                'lecturer' => 'ARIS NURHINDARTO, M.Kom',
                'schedule_type' => 'Academic',
                'status' => 'approved',
            ],
            [
                'room_id' => $roomD11->id,
                'activity_name' => 'AKUNTANSI MANAJEMEN',
                'class_name' => 'F13.601',
                'day_of_week' => 'Selasa',
                'start_time' => '09:30',
                'end_time' => '12:00',
                'lecturer' => 'Dr. ICHWAN SETIARSO, M.P.',
                'schedule_type' => 'Academic',
                'status' => 'approved',
            ],
            [
                'room_id' => $roomD11->id,
                'activity_name' => 'IMPLEMENTASI DAN PENGUJIAN',
                'class_name' => 'F12.D601',
                'day_of_week' => 'Selasa',
                'start_time' => '12:30',
                'end_time' => '14:10',
                'lecturer' => 'KARMILA, S.Si, M.Kom',
                'schedule_type' => 'Academic',
                'status' => 'approved',
            ],
            [
                'room_id' => $roomD11->id,
                'activity_name' => 'PROBABILITAS DAN STATISTIKA',
                'class_name' => 'F12.D202PL4',
                'day_of_week' => 'Selasa',
                'start_time' => '15:30',
                'end_time' => '18:00',
                'lecturer' => 'Dr. DIDIK HERMANTO, S.T., M.Pd',
                'schedule_type' => 'Academic',
                'status' => 'approved',
            ],
            [
                'room_id' => $roomD11->id,
                'activity_name' => 'LOGIKA INFORMATIKA',
                'class_name' => 'F11.C202',
                'day_of_week' => 'Rabu',
                'start_time' => '18:30',
                'end_time' => '21:00',
                'lecturer' => 'ACHMAD WAHID KURNIAWAN, S.Si, M.',
                'schedule_type' => 'Academic',
                'status' => 'approved',
            ],
            [
                'room_id' => $roomD11->id,
                'activity_name' => 'KECERDASAN BUATAN',
                'class_name' => 'F11.C402',
                'day_of_week' => 'Rabu',
                'start_time' => '15:30',
                'end_time' => '18:00',
                'lecturer' => 'MOCH. SJAMSUL HIDAJAT, S.E., M.M',
                'schedule_type' => 'Academic',
                'status' => 'approved',
            ],
            [
                'room_id' => $roomD11->id,
                'activity_name' => 'DASAR KEWIRAUSAHAAN',
                'class_name' => 'F14.E202',
                'day_of_week' => 'Kamis',
                'start_time' => '09:30',
                'end_time' => '12:00',
                'lecturer' => 'GALUH WILUJENG SARASWATI, M.MCS',
                'schedule_type' => 'Academic',
                'status' => 'approved',
            ],
            [
                'room_id' => $roomD11->id,
                'activity_name' => 'SEJARAH DKV',
                'class_name' => 'F14.E202',
                'day_of_week' => 'Kamis',
                'start_time' => '12:30',
                'end_time' => '14:00',
                'lecturer' => 'Dr. ICHWAN SETIARSO, M.P.',
                'schedule_type' => 'Academic',
                'status' => 'approved',
            ],
            [
                'room_id' => $roomD11->id,
                'activity_name' => 'INTERAKSI MANUSIA DAN KOM',
                'class_name' => 'F12.D202PL7',
                'day_of_week' => 'Kamis',
                'start_time' => '15:30',
                'end_time' => '18:00',
                'lecturer' => 'GALUH WILUJENG SARASWATI, M.MCS',
                'schedule_type' => 'Academic',
                'status' => 'approved',
            ],
            [
                'room_id' => $roomD11->id,
                'activity_name' => 'SISTEM TERDISTRIBUSI',
                'class_name' => 'F11.C601',
                'day_of_week' => 'Jumat',
                'start_time' => '16:20',
                'end_time' => '18:00',
                'lecturer' => 'MOCH. SJAMSUL HIDAJAT, S.E., M.M',
                'schedule_type' => 'Academic',
                'status' => 'approved',
            ],
            [
                'room_id' => $roomD11->id,
                'activity_name' => 'METODE PRODUKSI GRAFIKA',
                'class_name' => 'F14.E402',
                'day_of_week' => 'Jumat',
                'start_time' => '16:20',
                'end_time' => '18:00',
                'lecturer' => 'Dr. ICHWAN SETIARSO, M.P.',
                'schedule_type' => 'Academic',
                'status' => 'approved',
            ],
            [
                'room_id' => $roomD11->id,
                'activity_name' => 'IMPLEMENTASI DAN PENGUJIAN',
                'class_name' => 'F12.D602FPI22',
                'day_of_week' => 'Jumat',
                'start_time' => '18:30',
                'end_time' => '21:00',
                'lecturer' => 'WILDAN MAHMUD, S.Kom., M.MT',
                'schedule_type' => 'Academic',
                'status' => 'approved',
            ],
            [
                'room_id' => $roomD11->id,
                'activity_name' => 'MAGANG',
                'class_name' => 'F13.601',
                'day_of_week' => 'Sabtu',
                'start_time' => '09:30',
                'end_time' => '12:00',
                'lecturer' => 'MAHADIKA PRADIPTA HIMAWAN, S.Pa',
                'schedule_type' => 'Academic',
                'status' => 'approved',
            ],


            // Ruangan D1.2
            [
                'room_id' => $roomD12->id,
                'activity_name' => 'BASIS DATA',
                'class_name' => 'F11.C201',
                'day_of_week' => 'Senin',
                'start_time' => '09:30',
                'end_time' => '12:00',
                'lecturer' => 'ARIS NURHINDARTO, M.Kom',
                'schedule_type' => 'Academic',
                'status' => 'approved',
            ],
            [
                'room_id' => $roomD12->id,
                'activity_name' => 'SISTEM PENDUKUNG KEPUTUSAN',
                'class_name' => 'F12.D402PL8',
                'day_of_week' => 'Senin',
                'start_time' => '20:10',
                'end_time' => '21:50',
                'lecturer' => 'GALUH WILUJENG SARASWATI, M.MCS',
                'schedule_type' => 'Academic',
                'status' => 'approved',
            ],
            [
                'room_id' => $roomD12->id,
                'activity_name' => 'PEMASARAN DIGITAL',
                'class_name' => 'F13.601',
                'day_of_week' => 'Selasa',
                'start_time' => '09:30',
                'end_time' => '12:00',
                'lecturer' => 'CHOERUL UMAM, S.Kom., M.M',
                'schedule_type' => 'Academic',
                'status' => 'approved',
            ],
            [
                'room_id' => $roomD12->id,
                'activity_name' => 'ANALISA DAN PERANCANGAN S',
                'class_name' => 'F12.D401',
                'day_of_week' => 'Selasa',
                'start_time' => '14:10',
                'end_time' => '15:50',
                'lecturer' => 'ERBA LUTFINA, S.Kom, M.Kom',
                'schedule_type' => 'Academic',
                'status' => 'approved',
            ],
            [
                'room_id' => $roomD12->id,
                'activity_name' => 'ESTETIKA',
                'class_name' => 'F14.E202',
                'day_of_week' => 'Selasa',
                'start_time' => '16:20',
                'end_time' => '18:00',
                'lecturer' => 'Dr. ICHWAN SETIARSO, M.P.',
                'schedule_type' => 'Academic',
                'status' => 'approved',
            ],
            [
                'room_id' => $roomD12->id,
                'activity_name' => 'PERENCANAAN STRATEGIS SIS',
                'class_name' => 'F12.D402FPI25',
                'day_of_week' => 'Selasa',
                'start_time' => '18:30',
                'end_time' => '21:00',
                'lecturer' => 'WILDAN MAHMUD, S.Kom, M.MT',
                'schedule_type' => 'Academic',
                'status' => 'approved',
            ],
            [
                'room_id' => $roomD12->id,
                'activity_name' => 'KOMUNIKASI VISUAL PERIKLA',
                'class_name' => 'F14.E601',
                'day_of_week' => 'Rabu',
                'start_time' => '16:20',
                'end_time' => '18:00',
                'lecturer' => 'GILANG RIZKY GARDIANTO, S.DS, M.Kom',
                'schedule_type' => 'Academic',
                'status' => 'approved',
            ],
            [
                'room_id' => $roomD12->id,
                'activity_name' => 'KOMUNIKASI VISUAL PERIKLA',
                'class_name' => 'F14.E601',
                'day_of_week' => 'Rabu',
                'start_time' => '18:30',
                'end_time' => '20:10',
                'lecturer' => 'GILANG RIZKY GARDIANTO, S.DS, M.Kom',
                'schedule_type' => 'Academic',
                'status' => 'approved',
            ],
            [
                'room_id' => $roomD12->id,
                'activity_name' => 'METODE PRODUKSI GRAFIKA I',
                'class_name' => 'F14.E401',
                'day_of_week' => 'Kamis',
                'start_time' => '10:20',
                'end_time' => '12:00',
                'lecturer' => 'Dr. ICHWAN SETIARSO, M.P.',
                'schedule_type' => 'Academic',
                'status' => 'approved',
            ],
            [
                'room_id' => $roomD12->id,
                'activity_name' => 'ESTETIKA',
                'class_name' => 'F14.E201',
                'day_of_week' => 'Jumat',
                'start_time' => '10:20',
                'end_time' => '12:00',
                'lecturer' => 'Dr. ICHWAN SETIARSO, M.P.',
                'schedule_type' => 'Academic',
                'status' => 'approved',
            ],
            [
                'room_id' => $roomD12->id,
                'activity_name' => 'BAHASA INDONESIA',
                'class_name' => 'F14.E602',
                'day_of_week' => 'Jumat',
                'start_time' => '16:20',
                'end_time' => '18:00',
                'lecturer' => 'IQLIMA ZAHARI, S.Pd.I, M.Pd.I',
                'schedule_type' => 'Academic',
                'status' => 'approved',
            ],


            // Ruangan D1.3
            [
                'room_id' => $roomD13->id,
                'activity_name' => 'ALGORITMA DAN PEMROGRAMAN',
                'class_name' => 'F12.D201',
                'day_of_week' => 'Senin',
                'start_time' => '12:30',
                'end_time' => '14:10',
                'lecturer' => 'EKO HARI RACHMAWANTO, M.Kom',
                'schedule_type' => 'Academic',
                'status' => 'approved',
            ],
            [
                'room_id' => $roomD13->id,
                'activity_name' => 'INFRASTRUKTUR TEKNOLOGI I',
                'class_name' => 'F12.D202PL8',
                'day_of_week' => 'Senin',
                'start_time' => '16:20',
                'end_time' => '18:00',
                'lecturer' => 'CHOERUL UMAM, S.Kom., M.M',
                'schedule_type' => 'Academic',
                'status' => 'approved',
            ],
            [
                'room_id' => $roomD13->id,
                'activity_name' => 'ALGORITMA DAN PEMROGRAMAN',
                'class_name' => 'F12.D202PL6',
                'day_of_week' => 'Senin',
                'start_time' => '20:10',
                'end_time' => '21:50',
                'lecturer' => 'EKO HARI RACHMAWANTO, M.Kom',
                'schedule_type' => 'Academic',
                'status' => 'approved',
            ],
            [
                'room_id' => $roomD13->id,
                'activity_name' => 'MANAJEMEN RANTAI PASOK',
                'class_name' => 'F12.D401',
                'day_of_week' => 'Selasa',
                'start_time' => '09:30',
                'end_time' => '12:00',
                'lecturer' => 'ERBA LUTFINA, S.Kom, M.Kom',
                'schedule_type' => 'Academic',
                'status' => 'approved',
            ],
            [
                'room_id' => $roomD13->id,
                'activity_name' => 'KECERDASAN BUATAN',
                'class_name' => 'F11.C401',
                'day_of_week' => 'Selasa',
                'start_time' => '12:30',
                'end_time' => '16:00',
                'lecturer' => 'MOCH. SJAMSUL HIDAJAT, S.E., M.M',
                'schedule_type' => 'Academic',
                'status' => 'approved',
            ],
            [
                'room_id' => $roomD13->id,
                'activity_name' => 'FISIKA 1',
                'class_name' => 'F11.C201',
                'day_of_week' => 'Rabu',
                'start_time' => '08:40',
                'end_time' => '10:20',
                'lecturer' => 'Dr. DIDIK HERMANTO, S.T., M.Pd',
                'schedule_type' => 'Academic',
                'status' => 'approved',
            ],
            [
                'room_id' => $roomD13->id,
                'activity_name' => 'ANALISA DAN PERANCANGAN S',
                'class_name' => 'F12.D402HPL12',
                'day_of_week' => 'Rabu',
                'start_time' => '16:20',
                'end_time' => '18:00',
                'lecturer' => 'ERBA LUTFINA, S.Kom, M.Kom',
                'schedule_type' => 'Academic',
                'status' => 'approved',
            ],
            [
                'room_id' => $roomD13->id,
                'activity_name' => 'BASIS DATA',
                'class_name' => 'F12.D201',
                'day_of_week' => 'Kamis',
                'start_time' => '16:20',
                'end_time' => '18:00',
                'lecturer' => 'ERBA LUTFINA, S.Kom, M.Kom',
                'schedule_type' => 'Academic',
                'status' => 'approved',
            ],
            [
                'room_id' => $roomD13->id,
                'activity_name' => 'DESAIN KOMUNIKASI VISUAL',
                'class_name' => 'F14.E602',
                'day_of_week' => 'Kamis',
                'start_time' => '18:30',
                'end_time' => '20:10',
                'lecturer' => 'ADHITYA CANDRA IRAWAN, M.Sn',
                'schedule_type' => 'Academic',
                'status' => 'approved',
            ],
            [
                'room_id' => $roomD13->id,
                'activity_name' => 'ANALISA DAN PERANCANGAN S',
                'class_name' => 'F12.D402HPL2',
                'day_of_week' => 'Kamis',
                'start_time' => '20:10',
                'end_time' => '21:50',
                'lecturer' => 'ERBA LUTFINA, S.Kom, M.Kom',
                'schedule_type' => 'Academic',
                'status' => 'approved',
            ],
            [
                'room_id' => $roomD13->id,
                'activity_name' => 'PENDIDIKAN AGAMA ISLAM',
                'class_name' => 'F12.D601',
                'day_of_week' => 'Jumat',
                'start_time' => '10:20',
                'end_time' => '12:00',
                'lecturer' => 'IQLIMA ZAHARI, S.Pd.I, M.Pd.I',
                'schedule_type' => 'Academic',
                'status' => 'approved',
            ],
            [
                'room_id' => $roomD13->id,
                'activity_name' => 'MANAJEMEN RANTAI PASOK',
                'class_name' => 'F12.D202PL28',
                'day_of_week' => 'Jumat',
                'start_time' => '15:30',
                'end_time' => '18:00',
                'lecturer' => 'ERBA LUTFINA, S.Kom, M.Kom',
                'schedule_type' => 'Academic',
                'status' => 'approved',
            ],
            [
                'room_id' => $roomD13->id,
                'activity_name' => 'INFRASTRUKTUR TEKNOLOGI I',
                'class_name' => 'F12.D202PL8',
                'day_of_week' => 'Jumat',
                'start_time' => '18:30',
                'end_time' => '20:10',
                'lecturer' => 'CHOERUL UMAM, S.Kom., M.M',
                'schedule_type' => 'Academic',
                'status' => 'approved',
            ],


            // Ruangan D1.4
            // Ruangan C1.1
            [
                'room_id' => $roomC11->id,
                'activity_name' => 'TIPOGRAFI APLIKATIF',
                'class_name' => 'F14.E202',
                'day_of_week' => 'Senin',
                'start_time' => '18:30',
                'end_time' => '20:10',
                'lecturer' => 'ADHITYA CANDRA IRAWAN, M.Sn',
                'schedule_type' => 'Academic',
                'status' => 'approved',
            ],
            [
                'room_id' => $roomC11->id,
                'activity_name' => 'DESAIN KOMUNIKASI VISUAL',
                'class_name' => 'F14.E601',
                'day_of_week' => 'Selasa',
                'start_time' => '08:40',
                'end_time' => '10:20',
                'lecturer' => 'GILANG RIZKY GARDIANTO, S.DS, M.Kom',
                'schedule_type' => 'Academic',
                'status' => 'approved',
            ],
            [
                'room_id' => $roomC11->id,
                'activity_name' => 'DESAIN KOMUNIKASI VISUAL',
                'class_name' => 'F14.E601',
                'day_of_week' => 'Selasa',
                'start_time' => '10:20',
                'end_time' => '12:00',
                'lecturer' => 'GILANG RIZKY GARDIANTO, S.DS, M.Kom',
                'schedule_type' => 'Academic',
                'status' => 'approved',
            ],
            [
                'room_id' => $roomC11->id,
                'activity_name' => 'MENGGAMBAR I',
                'class_name' => 'F14.E202',
                'day_of_week' => 'Selasa',
                'start_time' => '18:30',
                'end_time' => '21:00',
                'lecturer' => 'KHAMADI, S.Sn, M.Ds',
                'schedule_type' => 'Academic',
                'status' => 'approved',
            ],
            [
                'room_id' => $roomC11->id,
                'activity_name' => 'MENGGAMBAR I',
                'class_name' => 'F14.E201',
                'day_of_week' => 'Rabu',
                'start_time' => '09:30',
                'end_time' => '12:00',
                'lecturer' => 'KHAMADI, S.Sn, M.Ds',
                'schedule_type' => 'Academic',
                'status' => 'approved',
            ],
            [
                'room_id' => $roomC11->id,
                'activity_name' => 'KOMUNIKASI GRAFIS',
                'class_name' => 'F14.E601',
                'day_of_week' => 'Rabu',
                'start_time' => '12:30',
                'end_time' => '14:10',
                'lecturer' => 'KHAMADI, S.Sn, M.Ds',
                'schedule_type' => 'Academic',
                'status' => 'approved',
            ],
            [
                'room_id' => $roomC11->id,
                'activity_name' => 'KOMUNIKASI GRAFIS',
                'class_name' => 'F14.E601',
                'day_of_week' => 'Rabu',
                'start_time' => '14:10',
                'end_time' => '15:50',
                'lecturer' => 'KHAMADI, S.Sn, M.Ds',
                'schedule_type' => 'Academic',
                'status' => 'approved',
            ],
            [
                'room_id' => $roomC11->id,
                'activity_name' => 'ILUSTRASI',
                'class_name' => 'F14.E402',
                'day_of_week' => 'Rabu',
                'start_time' => '16:20',
                'end_time' => '18:00',
                'lecturer' => 'KHAMADI, S.Sn, M.Ds',
                'schedule_type' => 'Academic',
                'status' => 'approved',
            ],
            [
                'room_id' => $roomC11->id,
                'activity_name' => 'ILUSTRASI',
                'class_name' => 'F14.E401',
                'day_of_week' => 'Kamis',
                'start_time' => '10:20',
                'end_time' => '12:00',
                'lecturer' => 'KHAMADI, S.Sn, M.Ds',
                'schedule_type' => 'Academic',
                'status' => 'approved',
            ],
            [
                'room_id' => $roomC11->id,
                'activity_name' => 'TIPOGRAFI APLIKATIF',
                'class_name' => 'F14.E201',
                'day_of_week' => 'Kamis',
                'start_time' => '12:30',
                'end_time' => '14:10',
                'lecturer' => 'ADHITYA CANDRA IRAWAN, M.Sn',
                'schedule_type' => 'Academic',
                'status' => 'approved',
            ],


            // Ruangan E2.1
            [
                'room_id' => $roomE21->id,
                'activity_name' => 'PRAKTIKUM MANAJEMEN OPERASI',
                'class_name' => 'F13.401',
                'day_of_week' => 'Senin',
                'start_time' => '07:00',
                'end_time' => '09:30',
                'lecturer' => 'MAHADIKA PRADIPTA HIMAWAN, S.Pa',
                'schedule_type' => 'Academic',
                'status' => 'approved',
            ],
            [
                'room_id' => $roomE21->id,
                'activity_name' => 'APLIKASI MOBILE',
                'class_name' => 'F12.D602RPL27',
                'day_of_week' => 'Senin',
                'start_time' => '16:20',
                'end_time' => '18:00',
                'lecturer' => 'ZUDHA PRATAMA, S.Kom., M.Kom',
                'schedule_type' => 'Academic',
                'status' => 'approved',
            ],
            [
                'room_id' => $roomE21->id,
                'activity_name' => 'E-DAGANG',
                'class_name' => 'F13.401',
                'day_of_week' => 'Selasa',
                'start_time' => '07:00',
                'end_time' => '08:40',
                'lecturer' => 'CHOERUL UMAM, S.Kom., M.M',
                'schedule_type' => 'Academic',
                'status' => 'approved',
            ],
            [
                'room_id' => $roomE21->id,
                'activity_name' => 'KOMPUTER GRAFIS I',
                'class_name' => 'F14.E201',
                'day_of_week' => 'Selasa',
                'start_time' => '10:20',
                'end_time' => '12:00',
                'lecturer' => 'KHAMADI, S.Sn, M.Ds',
                'schedule_type' => 'Academic',
                'status' => 'approved',
            ],
            [
                'room_id' => $roomE21->id,
                'activity_name' => 'DESAIN WEB',
                'class_name' => 'F14.E401',
                'day_of_week' => 'Selasa',
                'start_time' => '12:30',
                'end_time' => '14:10',
                'lecturer' => 'ANNAS MARZUKI SULAIMAN, M.Sn',
                'schedule_type' => 'Academic',
                'status' => 'approved',
            ],
            [
                'room_id' => $roomE21->id,
                'activity_name' => 'DESAIN WEB',
                'class_name' => 'F14.E402',
                'day_of_week' => 'Selasa',
                'start_time' => '16:20',
                'end_time' => '18:00',
                'lecturer' => 'ANNAS MARZUKI SULAIMAN, M.Sn',
                'schedule_type' => 'Academic',
                'status' => 'approved',
            ],
            [
                'room_id' => $roomE21->id,
                'activity_name' => 'PEMROGRAMAN BERORIENTASI',
                'class_name' => 'F11.C401',
                'day_of_week' => 'Rabu',
                'start_time' => '08:40',
                'end_time' => '10:20',
                'lecturer' => 'ZUDHA PRATAMA, S.Kom., M.Kom',
                'schedule_type' => 'Academic',
                'status' => 'approved',
            ],
            [
                'room_id' => $roomE21->id,
                'activity_name' => 'PEMROGRAMAN BERORIENTASI',
                'class_name' => 'F12.D401',
                'day_of_week' => 'Rabu',
                'start_time' => '10:20',
                'end_time' => '12:00',
                'lecturer' => 'ERBA LUTFINA, S.Kom, M.Kom',
                'schedule_type' => 'Academic',
                'status' => 'approved',
            ],
            [
                'room_id' => $roomE21->id,
                'activity_name' => 'ALGORITMA DAN PEMROGRAMAN',
                'class_name' => 'F11.C201',
                'day_of_week' => 'Rabu',
                'start_time' => '12:30',
                'end_time' => '14:10',
                'lecturer' => 'EKO HARI RACHMAWANTO, M.Kom',
                'schedule_type' => 'Academic',
                'status' => 'approved',
            ],
            [
                'room_id' => $roomE21->id,
                'activity_name' => 'APLIKASI KOMPUTER BISNIS',
                'class_name' => 'F13.202',
                'day_of_week' => 'Rabu',
                'start_time' => '16:20',
                'end_time' => '18:00',
                'lecturer' => 'WIDYATMOKO, S.Kom., M.M',
                'schedule_type' => 'Academic',
                'status' => 'approved',
            ],
            [
                'room_id' => $roomE21->id,
                'activity_name' => 'ALGORITMA DAN PEMROGRAMAN',
                'class_name' => 'F11.C202',
                'day_of_week' => 'Rabu',
                'start_time' => '16:30',
                'end_time' => '20:10',
                'lecturer' => 'EKO HARI RACHMAWANTO, M.Kom',
                'schedule_type' => 'Academic',
                'status' => 'approved',
            ],
            [
                'room_id' => $roomE21->id,
                'activity_name' => 'APLIKASI MOBILE',
                'class_name' => 'F12.D602RPL27',
                'day_of_week' => 'Rabu',
                'start_time' => '20:10',
                'end_time' => '21:50',
                'lecturer' => 'ZUDHA PRATAMA, S.Kom., M.Kom',
                'schedule_type' => 'Academic',
                'status' => 'approved',
            ],
            [
                'room_id' => $roomE21->id,
                'activity_name' => 'PEMODELAN 3D',
                'class_name' => 'F14.C601',
                'day_of_week' => 'Kamis',
                'start_time' => '12:30',
                'end_time' => '14:10',
                'lecturer' => 'DIMAS IRAWAN IHYA, ULMUDDIN, S.M',
                'schedule_type' => 'Academic',
                'status' => 'approved',
            ],
            [
                'room_id' => $roomE21->id,
                'activity_name' => 'PEMODELAN 3D',
                'class_name' => 'F14.E602',
                'day_of_week' => 'Kamis',
                'start_time' => '18:30',
                'end_time' => '20:10',
                'lecturer' => 'ALI MUGODDAS, S.Sn, M.Kom',
                'schedule_type' => 'Academic',
                'status' => 'approved',
            ],
            [
                'room_id' => $roomE21->id,
                'activity_name' => 'PEMROGRAMAN WEB LANJUT',
                'class_name' => 'F11.C202',
                'day_of_week' => 'Jumat',
                'start_time' => '16:20',
                'end_time' => '18:00',
                'lecturer' => 'ZUDHA PRATAMA, S.Kom., M.Kom',
                'schedule_type' => 'Academic',
                'status' => 'approved',
            ],


            // Ruangan E2.2
            [
                'room_id' => $roomE22->id,
                'activity_name' => 'KOMPUTER GRAFIS I',
                'class_name' => 'F14.E202',
                'day_of_week' => 'Senin',
                'start_time' => '16:20',
                'end_time' => '18:00',
                'lecturer' => 'KHAMADI, S.Sn, M.Ds',
                'schedule_type' => 'Academic',
                'status' => 'approved',
            ],
            [
                'room_id' => $roomE22->id,
                'activity_name' => 'ANIMASI 2D',
                'class_name' => 'F14.E602',
                'day_of_week' => 'Senin',
                'start_time' => '18:30',
                'end_time' => '20:10',
                'lecturer' => 'DIMAS IRAWAN IHYA ULMUDDIN, S.',
                'schedule_type' => 'Academic',
                'status' => 'approved',
            ],
            [
                'room_id' => $roomE22->id,
                'activity_name' => 'ANIMASI 2D',
                'class_name' => 'F14.E601',
                'day_of_week' => 'Selasa',
                'start_time' => '12:00',
                'end_time' => '14:10',
                'lecturer' => 'ALI MUQODDAS, S.Sn, M.Kom',
                'schedule_type' => 'Academic',
                'status' => 'approved',
            ],
            [
                'room_id' => $roomE22->id,
                'activity_name' => 'ALGORITMA DAN PEMROGRAMAN',
                'class_name' => 'F12.D201',
                'day_of_week' => 'Selasa',
                'start_time' => '14:10',
                'end_time' => '15:50',
                'lecturer' => 'EKO HARI RACHMAWANTO, M.Kom',
                'schedule_type' => 'Academic',
                'status' => 'approved',
            ],
            [
                'room_id' => $roomE22->id,
                'activity_name' => 'PEMROGRAMAN WEB',
                'class_name' => 'F12.D401',
                'day_of_week' => 'Selasa',
                'start_time' => '16:20',
                'end_time' => '18:00',
                'lecturer' => 'ZUDHA PRATAMA, S.Kom, M.Kom',
                'schedule_type' => 'Academic',
                'status' => 'approved',
            ],
            [
                'room_id' => $roomE22->id,
                'activity_name' => 'ALGORITMA DAN PEMROGRAMAN',
                'class_name' => 'F12.D202HPL6',
                'day_of_week' => 'Selasa',
                'start_time' => '18:30',
                'end_time' => '20:10',
                'lecturer' => 'EKO HARI RACHMAWANTO, M.Kom',
                'schedule_type' => 'Academic',
                'status' => 'approved',
            ],
            [
                'room_id' => $roomE22->id,
                'activity_name' => 'ANALISIS MULTIVARIAT',
                'class_name' => 'F13.401',
                'day_of_week' => 'Rabu',
                'start_time' => '09:30',
                'end_time' => '12:00',
                'lecturer' => 'WANA PRAMUDYAWARDANA KUSUMA NEG.',
                'schedule_type' => 'Academic',
                'status' => 'approved',
            ],
            [
                'room_id' => $roomE22->id,
                'activity_name' => 'APLIKASI KOMPUTER BISNIS',
                'class_name' => 'F13.201',
                'day_of_week' => 'Rabu',
                'start_time' => '12:30',
                'end_time' => '14:10',
                'lecturer' => 'WIDYATMOKO, S.Kom., M.M',
                'schedule_type' => 'Academic',
                'status' => 'approved',
            ],
            [
                'room_id' => $roomE22->id,
                'activity_name' => 'PEMROGRAMAN WEB',
                'class_name' => 'F12.D401',
                'day_of_week' => 'Rabu',
                'start_time' => '16:20',
                'end_time' => '18:00',
                'lecturer' => 'ZUDHA PRATAMA, S.Kom, M.Kom',
                'schedule_type' => 'Academic',
                'status' => 'approved',
            ],
            [
                'room_id' => $roomE22->id,
                'activity_name' => 'PEMROGRAMAN BERORIENTASI',
                'class_name' => 'F11.C402',
                'day_of_week' => 'Rabu',
                'start_time' => '16:30',
                'end_time' => '20:10',
                'lecturer' => 'ZUDHA PRATAMA, S.Kom, M.Kom',
                'schedule_type' => 'Academic',
                'status' => 'approved',
            ],
            [
                'room_id' => $roomE22->id,
                'activity_name' => 'PEMROGRAMAN BERORIENTASI',
                'class_name' => 'F12.D401',
                'day_of_week' => 'Kamis',
                'start_time' => '08:40',
                'end_time' => '10:20',
                'lecturer' => 'ERBA LUTFINA, S.Kom, M.Kom',
                'schedule_type' => 'Academic',
                'status' => 'approved',
            ],
            [
                'room_id' => $roomE22->id,
                'activity_name' => 'PEMROGRAMAN WEB 2',
                'class_name' => 'F12.D201',
                'day_of_week' => 'Kamis',
                'start_time' => '10:20',
                'end_time' => '12:00',
                'lecturer' => 'ZUDHA PRATAMA, S.Kom., M.Kom',
                'schedule_type' => 'Academic',
                'status' => 'approved',
            ],
            [
                'room_id' => $roomE22->id,
                'activity_name' => 'PEMROGRAMAN WEB LANJUT',
                'class_name' => 'F11.C201',
                'day_of_week' => 'Kamis',
                'start_time' => '12:30',
                'end_time' => '14:10',
                'lecturer' => 'ZUDHA PRATAMA, S.Kom., M.Kom',
                'schedule_type' => 'Academic',
                'status' => 'approved',
            ],
            [
                'room_id' => $roomE22->id,
                'activity_name' => 'MANAJEMEN BIG DATA',
                'class_name' => 'F12.D602RPL17',
                'day_of_week' => 'Kamis',
                'start_time' => '18:30',
                'end_time' => '20:10',
                'lecturer' => 'Dr. FARRIKH AL ZAMI, M.Kom',
                'schedule_type' => 'Academic',
                'status' => 'approved',
            ],
            [
                'room_id' => $roomE22->id,
                'activity_name' => 'PEMROGRAMAN WEB',
                'class_name' => 'F12.D201',
                'day_of_week' => 'Jumat',
                'start_time' => '12:30',
                'end_time' => '14:10',
                'lecturer' => 'ZUDHA PRATAMA, S.Kom., M.Kom',
                'schedule_type' => 'Academic',
                'status' => 'approved',
            ],


        ];

        // Menyimpan data ke dalam tabel RoomSchedule
        foreach ($data as $schedule) {
            RoomSchedule::create($schedule);
        }
    }
}
